from datetime import datetime

from pydantic import BaseModel, Field


class QuizQuestion(BaseModel):
    """A single quiz question with multiple choice options."""

    question: str = Field(..., description="The question text")
    options: list[str] = Field(..., min_length=2, description="List of answer options")
    correct_index: int = Field(..., ge=0, description="Index of the correct option")
    explanation: str = Field(..., description="Explanation of the correct answer")


class ContentSection(BaseModel):
    """A single section of learning content."""

    title: str = Field(..., description="Section title")
    narration_text: str = Field(..., description="Full narration text for this section")
    image_prompt: str = Field(..., description="Prompt for generating the section image")


class GeneratedContent(BaseModel):
    """Complete structured learning content generated by the LLM."""

    title: str = Field(..., description="Overall lesson title")
    overview: str = Field(..., description="Brief overview of the topic")
    sections: list[ContentSection] = Field(
        ..., min_length=1, description="Ordered list of content sections"
    )
    quiz_questions: list[QuizQuestion] = Field(
        default_factory=list, description="Quiz questions for comprehension check"
    )


class TopicExploreRequest(BaseModel):
    """Request to explore a new learning topic."""

    user_id: int = Field(..., gt=0, description="ID of the user requesting content")
    topic: str = Field(..., min_length=1, max_length=500, description="Topic to explore")


class TopicExploreResponse(BaseModel):
    """Response from topic exploration with full generated content."""

    session_id: int
    user_id: int
    topic: str
    status: str
    generated_content: GeneratedContent | None
    created_at: datetime

    model_config = {"from_attributes": True}


class GenerateVideoRequest(BaseModel):
    """Request to generate a video for a learning session."""

    session_id: int = Field(..., gt=0)


class GenerateVideoResponse(BaseModel):
    """Response after video generation."""

    session_id: int
    status: str
    video_path: str | None = None
    video_url: str | None = None
    message: str = ""


class GenerateSlidesRequest(BaseModel):
    """Request to generate a PPTX slideshow for a learning session."""

    session_id: int = Field(..., gt=0)


class GenerateSlidesResponse(BaseModel):
    """Response after slideshow generation."""

    session_id: int
    status: str
    slides_path: str | None = None
    slides_url: str | None = None
    message: str = ""


class QuizSubmitRequest(BaseModel):
    """Request to submit quiz answers."""

    answers: list[int] = Field(..., description="List of selected option indices, one per question")


class QuizSubmitResponse(BaseModel):
    """Response after quiz submission with score."""

    session_id: int
    total: int
    correct: int
    score: float = Field(..., description="Percentage score 0-100")
    results: list[dict] = Field(
        default_factory=list,
        description="Per-question result details with correctness and explanation",
    )
