from datetime import datetime

from pydantic import BaseModel, Field


class QuizQuestion(BaseModel):
    """A single quiz question with multiple choice options."""

    question: str = Field(..., description="The question text")
    options: list[str] = Field(..., min_length=2, description="List of answer options")
    correct_index: int = Field(..., ge=0, description="Index of the correct option")
    explanation: str = Field(..., description="Explanation of the correct answer")


class ContentSection(BaseModel):
    """A single section of learning content."""

    title: str = Field(..., description="Section title")
    narration_text: str = Field(..., description="Full narration text for this section")
    image_prompts: list[str] = Field(
        default_factory=list, description="2-3 image prompts for this section"
    )
    # Backwards compat: accept old single image_prompt
    image_prompt: str = Field(default="", description="Deprecated: use image_prompts")


class GeneratedContent(BaseModel):
    """Complete structured learning content generated by the LLM."""

    title: str = Field(..., description="Overall lesson title")
    overview: str = Field(..., description="Brief overview of the topic")
    sections: list[ContentSection] = Field(
        ..., min_length=1, description="Ordered list of content sections"
    )
    quiz_questions: list[QuizQuestion] = Field(
        default_factory=list, description="Quiz questions for comprehension check"
    )


class TopicExploreRequest(BaseModel):
    """Request to explore a new learning topic."""

    user_id: int = Field(..., gt=0, description="ID of the user requesting content")
    topic: str = Field(..., min_length=1, max_length=500, description="Topic to explore")
    mode: str = Field(
        default="short", description="Content mode: 'short' (1-2 min) or 'long' (5-8 min)"
    )
    image_style: str | None = Field(default=None, description="Per-lesson image style override")
    image_provider: str | None = Field(
        default=None, description="Image provider: 'grok' (default) or 'fuseapi'"
    )
    session_id: int | None = Field(default=None, description="Resume from an assessed session")


class TopicExploreResponse(BaseModel):
    """Response from topic exploration with full generated content."""

    session_id: int
    user_id: int
    topic: str
    status: str
    generated_content: GeneratedContent | None
    created_at: datetime

    model_config = {"from_attributes": True}


class SessionIdRequest(BaseModel):
    """Generic request with just a session_id."""

    session_id: int = Field(..., gt=0)


class GenerateSectionAudioRequest(BaseModel):
    """Request to generate audio for a single section."""

    session_id: int = Field(..., gt=0)
    section_index: int = Field(..., ge=0)
    text: str = Field(..., min_length=1)


class GenerateSectionAudioResponse(BaseModel):
    """Response after generating section audio."""

    audio_url: str


class StepResponse(BaseModel):
    """Generic response for a pipeline step."""

    session_id: int
    status: str
    message: str = ""


class GenerateImagesResponse(StepResponse):
    image_paths: list[str] = []


class GenerateVoiceResponse(StepResponse):
    audio_path: str | None = None


class GenerateVideoRequest(BaseModel):
    session_id: int = Field(..., gt=0)
    use_animated: bool | None = Field(
        default=None,
        description="Use animated clips. None = auto-detect from image style.",
    )


class GenerateVideoResponse(StepResponse):
    video_path: str | None = None
    video_url: str | None = None


class GenerateSlidesRequest(BaseModel):
    """Request to generate a PPTX slideshow for a learning session."""

    session_id: int = Field(..., gt=0)


class GenerateSlidesResponse(BaseModel):
    """Response after slideshow generation."""

    session_id: int
    status: str
    slides_path: str | None = None
    slides_url: str | None = None
    message: str = ""


class SessionSummary(BaseModel):
    """Lightweight session info for listing."""

    id: int
    user_id: int
    topic: str
    status: str
    image_style: str | None = None
    video_path: str | None = None
    slides_path: str | None = None
    concepts_learned: list[str] | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class SessionResponse(BaseModel):
    """Full session state with all pipeline artifacts."""

    id: int
    user_id: int
    topic: str
    status: str
    image_style: str | None = None
    search_results: list[dict] | None = None
    generated_content: GeneratedContent | None = None
    image_paths: list[str] | None = None
    video_path: str | None = None
    slides_path: str | None = None
    error_message: str | None = None
    concepts_learned: list[str] | None = None
    assessment_qa: dict | None = None
    assessment_summary: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class QuizSubmitRequest(BaseModel):
    """Request to submit quiz answers."""

    answers: list[int] = Field(..., description="List of selected option indices, one per question")


class QuizSubmitResponse(BaseModel):
    """Response after quiz submission with score."""

    session_id: int
    total: int
    correct: int
    score: float = Field(..., description="Percentage score 0-100")
    results: list[dict] = Field(
        default_factory=list,
        description="Per-question result details with correctness and explanation",
    )
